using UnityEngine;
using UnityEngine.EventSystems;

namespace eagle {
    public class CommandInfoButtonHoverController : MonoBehaviour,
                                                    IPointerEnterHandler,
                                                    IPointerExitHandler {
        public CommandPanelController commandPanelController;

        public void OnPointerEnter(PointerEventData eventData) {
            commandPanelController.InfoButtonHovered();
        }

        public void OnPointerExit(PointerEventData eventData) {
            commandPanelController.InfoButtonExited();
        }
    }
}
