using UnityEngine;

namespace eagle {
    public class KeyModifiedAmount {
        private static bool Shift() {
            return Input.GetKey(KeyCode.LeftShift) || Input.GetKey(KeyCode.RightShift);
        }
        private static bool Control() {
            return Input.GetKey(KeyCode.LeftControl) || Input.GetKey(KeyCode.RightControl);
        }

        public static int Amount() {
            if (Shift() && Control()) { return 1000; }
            if (Shift()) { return 100; }
            if (Control()) { return 10; }
            return 1;
        }
    }
}